version: '3'

vars:
  CLUSTER_NAME: meta-secret-dev
  CONFIG_FILE: k3d-config-dev.yaml
  REGISTRY_NAME: meta-secret-registry
  REGISTRY_PORT: 5000

tasks:
  create-cluster:
    desc: Create a k3d cluster with the specified config
    cmds:
      - echo "Creating k3d cluster '{{.CLUSTER_NAME}}' with config '{{.CONFIG_FILE}}'"
      - k3d cluster create --config {{.CONFIG_FILE}}

  delete-cluster:
    desc: Delete the k3d cluster
    cmds:
      - echo "Deleting k3d cluster '{{.CLUSTER_NAME}}'"
      - k3d cluster delete {{.CLUSTER_NAME}}

  get-kubeconfig:
    desc: Get kubeconfig for the k3d cluster
    cmds:
      - echo "Getting kubeconfig for the k3d cluster '{{.CLUSTER_NAME}}'"
      - k3d kubeconfig get {{.CLUSTER_NAME}} 