#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
GLOSSARY="$ROOT_DIR/.ai/GLOSSARY.md"
CONSTRAINTS="$ROOT_DIR/.ai/CONSTRAINTS.md"

require_text() {
  local file="$1"
  local expected="$2"
  if ! grep -Fq -- "$expected" "$file"; then
    echo "Missing documentation text in ${file#$ROOT_DIR/}: $expected" >&2
    exit 1
  fi
}

require_text "$GLOSSARY" 'randomly generated by Core from the operating system CSPRNG'
require_text "$GLOSSARY" '**Encrypted Key Share**'
require_text "$CONSTRAINTS" 'Keep remote Encrypted Key Shares only as temporary outbound workflows'

# Protocol terminology must use "Encrypted Key Share". Signed protocol
# envelopes remain valid terminology, so only the ambiguous encrypted forms
# are rejected here.
if rg -n -i \
  --glob '*.md' --glob '*.rs' --glob '*.vue' --glob '*.ts' --glob '*.kt' \
  --glob '!**/.ai/artifacts/**' --glob '!**/target/**' --glob '!**/build/**' \
  'encrypted[[:space:]-]+(share|shares|envelope|envelopes)|зашифрованн[^[:space:]]*[[:space:]]+конверт' \
  "$ROOT_DIR/.ai" "$ROOT_DIR/docs" "$ROOT_DIR/meta-secret"; then
  echo 'Ambiguous encrypted-share/envelope terminology found; use Encrypted Key Share.' >&2
  exit 1
fi

# Master Key generation is random and independent of password KDFs.
if rg -n -i \
  --glob '*.md' --glob '*.rs' --glob '*.vue' --glob '*.ts' --glob '*.kt' \
  --glob '!**/.ai/artifacts/**' --glob '!**/target/**' --glob '!**/build/**' \
  'Master[[:space:]]+Key[[:space:]]+(uses|is[[:space:]]+derived|derives[[:space:]]+from)|Master[[:space:]]+key[[:space:]]+derivation' \
  "$ROOT_DIR/.ai" "$ROOT_DIR/docs" "$ROOT_DIR/meta-secret"; then
  echo 'Stale password-derived Master Key documentation found.' >&2
  exit 1
fi

echo 'Core documentation terminology and Master Key lifecycle are consistent.'
