VERSION 0.8
FROM scratch

taskomatic-base-build:
    FROM python:3.12-bookworm

    RUN apt update && apt install -y build-essential curl wget
    RUN wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    ENV TASKOMATIC_DIR=/taskomatic
    WORKDIR ${TASKOMATIC_DIR}

    SAVE IMAGE localhost/taskomatic:latest

taskomatic-k3d-build:
    FROM +taskomatic-base-build
    ENV TASKOMATIC_DIR=/taskomatic
    WORKDIR ${TASKOMATIC_DIR}/k3d
    COPY k3d .
    CMD ["--list"]
    SAVE IMAGE localhost/taskomatic-k3d:latest

taskomatic-k3d-run:
    ARG task
    LOCALLY
    WITH DOCKER --load=+taskomatic-build
        RUN --no-cache docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --name taskomatic \
            localhost/taskomatic:latest ${task}
    END

build-taskomatic-ai:
    FROM +taskomatic-base-build

    ENV TASKOMATIC_DIR=/taskomatic
    WORKDIR ${TASKOMATIC_DIR}/ai

    COPY ./.aider.conf.yml .
    COPY ./.env .

    RUN pip install --upgrade pip setuptools && pip install aider-chat
    # Verify aider installation works
    RUN aider --help

    SAVE IMAGE localhost/taskomatic-ai:latest

taskomatic-k8s-build:
    FROM +taskomatic-base-build
    WORKDIR ${TASKOMATIC_DIR}/k8s
    COPY k8s .
    RUN --no-cache kcl
    SAVE IMAGE localhost/taskomatic-k8s:latest

build-sops:
    FROM quay.io/getsops/sops:v3.9.4
    RUN apt update && apt install -y build-essential age curl tar

    #Install age
    ENV AGE_VERSION=v1.2.1
    ENV AGE_ARCHIVE=age-${AGE_VERSION}-linux-amd64.tar.gz
    ENV AGE_RELEASES_PAGE=https://github.com/FiloSottile/age/releases
    RUN curl -LO ${AGE_RELEASES_PAGE}/download/${AGE_VERSION}/${AGE_ARCHIVE} && \
        tar -xzf ${AGE_ARCHIVE} && \
        mv age/age age/age-keygen /usr/local/bin/ && \
        rm -rf age ${AGE_ARCHIVE}

    RUN --no-cache age --version