#cloud-config

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - git
  - curl
  - wget
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Add Docker's official GPG key and repository
write_files:
  - path: /etc/apt/keyrings/docker.gpg
    permissions: '0644'
    defer: true
    content: |
      # This will be populated during runcmd

  - path: /etc/apt/sources.list.d/docker.list
    permissions: '0644'
    defer: true
    content: |
      # This will be populated during runcmd

  - path: /etc/apt/keyrings/kubernetes.gpg
    permissions: '0644'
    defer: true
    content: |
      # This will be populated during runcmd

  - path: /etc/apt/sources.list.d/kubernetes.list
    permissions: '0644'
    defer: true
    content: |
      # This will be populated during runcmd

# Run commands to set up repositories and install packages
runcmd:
  # Set up Docker repository
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  
  # Install Docker
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  
  # Start and enable Docker service
  - systemctl enable docker
  - systemctl start docker
  
  # Set up Kubernetes repository
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  
  # Install kubectl
  - apt-get update
  - apt-get install -y kubectl
  
  # Install k3d
  - curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  
  # Add Docker group to current user
  - usermod -aG docker $USER

# Final system configuration
final_message: "The system is now prepared with git, docker, curl, wget, k3d, and kubectl"
