[bindings.swift]
module_name = "MetaCore"
ffi_module_name = "MetaCoreFFI"

generate_immutable_records = true
generate_codable_conformance = true
generate_case_iterable_conformance = true

[bindings.kotlin]
package_name = "build.metasecret.rust.core"
cdylib_name = "core"
