[package]
name = "meta-secret-cli"
version = "1.1.0"
edition = "2021"

[dependencies]
meta-secret-core = "1.2.6"
clap = { version = "3.2", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0.33"

serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
