[package]
name = "meta-secret-core"
version = "1.2.6"
edition = "2021"
license = "Apache-2.0"
description = "Meta Secret core module"
homepage = "https://github.com/meta-secret/meta-secret-node/tree/main/core"
documentation = "https://github.com/meta-secret/meta-secret-node/blob/main/core/README.md"
repository = "https://github.com/meta-secret/meta-secret-node/blob/main/core/README.md"
readme = "README.md"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]
name = "meta_secret_core"

[dependencies]
thiserror = "1.0"

ed25519-dalek = "1.0"
crypto_box = "0.8.1"
rand = "0.7"

#https://github.com/dsprenkels/sss-rs
shamirsecretsharing = "0.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
serde-big-array = "0.4"

base64 = "0.20.0-alpha.1"

qrcode-generator = "4.1"
rqrr = "0.5"
image = "0.24"
