[package]
name = "meta-secret-cli"
version = "1.1.0"
edition = "2021"

[dependencies]
meta-secret-core = { path = "../core" }

thiserror.workspace = true
anyhow.workspace = true

clap = { version = "3.2.25", features = ["derive"] }

serde.workspace = true
serde_yaml.workspace = true
