openapi: 3.0.2
info:
  title: Meta Secret Core Models
  version: 1.0.0

x-cargo-authors:
  - bynull <bynull@meta-secret.org>

components:
  schemas:
    Fundamental:
      type: object
      required:
        - statement
      properties:
        statement:
          type: string
    # Encryption



paths:
