[package]
name = "meta-secret-core-swift"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "meta_secret_core_swift"

[dependencies]
meta-secret-core = "1.2.6"
#meta-secret-core = { path = "../../core"} # Development mode
serde_json = "1.0.87"
