/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AeadPlainText {
    #[serde(rename = "msg")]
    pub msg: Box<crate::models::Base64EncodedText>,
    #[serde(rename = "authData")]
    pub auth_data: Box<crate::models::AeadAuthData>,
}

impl AeadPlainText {
    pub fn new(msg: crate::models::Base64EncodedText, auth_data: crate::models::AeadAuthData) -> AeadPlainText {
        AeadPlainText {
            msg: Box::new(msg),
            auth_data: Box::new(auth_data),
        }
    }
}
