/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AppCommandType : Update: The event that contains data and just updates the database (essentially this is an event          that happens as a result of an action that was executed, see Genesis, SingUp and other commands). 

/// Update: The event that contains data and just updates the database (essentially this is an event          that happens as a result of an action that was executed, see Genesis, SingUp and other commands). 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AppCommandType {
    #[serde(rename = "Update")]
    Update,
    #[serde(rename = "Genesis")]
    Genesis,
    #[serde(rename = "SignUp")]
    SignUp,
    #[serde(rename = "JoinCluster")]
    JoinCluster,

}

impl ToString for AppCommandType {
    fn to_string(&self) -> String {
        match self {
            Self::Update => String::from("Update"),
            Self::Genesis => String::from("Genesis"),
            Self::SignUp => String::from("SignUp"),
            Self::JoinCluster => String::from("JoinCluster"),
        }
    }
}

impl Default for AppCommandType {
    fn default() -> AppCommandType {
        Self::Update
    }
}




