/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationState {
    #[serde(rename = "metaVault", skip_serializing_if = "Option::is_none")]
    pub meta_vault: Option<Box<crate::models::MetaVault>>,
    #[serde(rename = "vault", skip_serializing_if = "Option::is_none")]
    pub vault: Option<Box<crate::models::VaultDoc>>,
    #[serde(rename = "joinComponent")]
    pub join_component: bool,
}

impl ApplicationState {
    pub fn new(join_component: bool) -> ApplicationState {
        ApplicationState {
            meta_vault: None,
            vault: None,
            join_component,
        }
    }
}
