/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EncryptedMessage {
    #[serde(rename = "receiver")]
    pub receiver: Box<crate::models::UserSignature>,
    #[serde(rename = "encryptedText")]
    pub encrypted_text: Box<crate::models::AeadCipherText>,
}

impl EncryptedMessage {
    pub fn new(
        receiver: crate::models::UserSignature,
        encrypted_text: crate::models::AeadCipherText,
    ) -> EncryptedMessage {
        EncryptedMessage {
            receiver: Box::new(receiver),
            encrypted_text: Box::new(encrypted_text),
        }
    }
}
