/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FindSharesRequest {
    #[serde(rename = "userRequestType")]
    pub user_request_type: crate::models::SecretDistributionType,
    #[serde(rename = "userSignature")]
    pub user_signature: Box<crate::models::UserSignature>,
}

impl FindSharesRequest {
    pub fn new(
        user_request_type: crate::models::SecretDistributionType,
        user_signature: crate::models::UserSignature,
    ) -> FindSharesRequest {
        FindSharesRequest {
            user_request_type,
            user_signature: Box::new(user_signature),
        }
    }
}
