/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KvKey {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "store")]
    pub store: String,
}

impl KvKey {
    pub fn new(id: String, store: String) -> KvKey {
        KvKey {
            id,
            store,
        }
    }
}


