/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KvLogEvent {
    #[serde(rename = "key")]
    pub key: Box<crate::models::KvKey>,
    #[serde(rename = "cmdType")]
    pub cmd_type: crate::models::AppCommandType,
    #[serde(rename = "valType")]
    pub val_type: crate::models::KvValueType,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl KvLogEvent {
    pub fn new(key: crate::models::KvKey, cmd_type: crate::models::AppCommandType, val_type: crate::models::KvValueType) -> KvLogEvent {
        KvLogEvent {
            key: Box::new(key),
            cmd_type,
            val_type,
            value: None,
        }
    }
}


