/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KvValueType {
    #[serde(rename = "DsaPublicKey")]
    DsaPublicKey,
    #[serde(rename = "UserSignature")]
    UserSignature,
    #[serde(rename = "Vault")]
    Vault,
    #[serde(rename = "Error")]
    Error,

}

impl ToString for KvValueType {
    fn to_string(&self) -> String {
        match self {
            Self::DsaPublicKey => String::from("DsaPublicKey"),
            Self::UserSignature => String::from("UserSignature"),
            Self::Vault => String::from("Vault"),
            Self::Error => String::from("Error"),
        }
    }
}

impl Default for KvValueType {
    fn default() -> KvValueType {
        Self::DsaPublicKey
    }
}




