/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// MembershipStatus : `AlreadyMember`: Device is a member of a vault already. `Finished`: Operation finished successfully.

/// `AlreadyMember`: Device is a member of a vault already. `Finished`: Operation finished successfully.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MembershipStatus {
    #[serde(rename = "VaultNotFound")]
    VaultNotFound,
    #[serde(rename = "AlreadyMember")]
    AlreadyMember,
    #[serde(rename = "Finished")]
    Finished,
}

impl ToString for MembershipStatus {
    fn to_string(&self) -> String {
        match self {
            Self::VaultNotFound => String::from("VaultNotFound"),
            Self::AlreadyMember => String::from("AlreadyMember"),
            Self::Finished => String::from("Finished"),
        }
    }
}

impl Default for MembershipStatus {
    fn default() -> MembershipStatus {
        Self::VaultNotFound
    }
}
