/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MetaVault : It keeps the information about a vault.  It's the origin of the objects generated to create a user vault and generate all necessary credentials and user signatures. MetaVault -> KeyManager -> UserSignature 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetaVault {
    #[serde(rename = "vaultName")]
    pub vault_name: String,
    #[serde(rename = "device")]
    pub device: Box<crate::models::DeviceInfo>,
}

impl MetaVault {
    /// It keeps the information about a vault.  It's the origin of the objects generated to create a user vault and generate all necessary credentials and user signatures. MetaVault -> KeyManager -> UserSignature 
    pub fn new(vault_name: String, device: crate::models::DeviceInfo) -> MetaVault {
        MetaVault {
            vault_name,
            device: Box::new(device),
        }
    }
}


