/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaPasswordDoc {
    #[serde(rename = "id")]
    pub id: Box<crate::models::MetaPasswordId>,
    #[serde(rename = "vault")]
    pub vault: Box<crate::models::VaultDoc>,
}

impl MetaPasswordDoc {
    pub fn new(id: crate::models::MetaPasswordId, vault: crate::models::VaultDoc) -> MetaPasswordDoc {
        MetaPasswordDoc {
            id: Box::new(id),
            vault: Box::new(vault),
        }
    }
}
