/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetaPasswordId {
    /// SHA256 hash of a salt
    #[serde(rename = "id")]
    pub id: String,
    /// Random String up to 30 characters, must be unique
    #[serde(rename = "salt")]
    pub salt: String,
    /// Human readable name given to the password
    #[serde(rename = "name")]
    pub name: String,
}

impl MetaPasswordId {
    pub fn new(id: String, salt: String, name: String) -> MetaPasswordId {
        MetaPasswordId {
            id,
            salt,
            name,
        }
    }
}


