/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetaPasswordsStatus {
    #[serde(rename = "Ok")]
    Ok,
    #[serde(rename = "VaultNotFound")]
    VaultNotFound,
}

impl ToString for MetaPasswordsStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Ok => String::from("Ok"),
            Self::VaultNotFound => String::from("VaultNotFound"),
        }
    }
}

impl Default for MetaPasswordsStatus {
    fn default() -> MetaPasswordsStatus {
        Self::Ok
    }
}
