/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetaPasswordsData {
    #[serde(rename = "passwordStatus")]
    pub password_status: crate::models::MetaPasswordsStatus,
    #[serde(rename = "passwords")]
    pub passwords: Vec<crate::models::MetaPasswordDoc>,
}

impl MetaPasswordsData {
    pub fn new(
        password_status: crate::models::MetaPasswordsStatus,
        passwords: Vec<crate::models::MetaPasswordDoc>,
    ) -> MetaPasswordsData {
        MetaPasswordsData {
            password_status,
            passwords,
        }
    }
}
