/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecretDistributionType {
    #[serde(rename = "Split")]
    Split,
    #[serde(rename = "Recover")]
    Recover,

}

impl ToString for SecretDistributionType {
    fn to_string(&self) -> String {
        match self {
            Self::Split => String::from("Split"),
            Self::Recover => String::from("Recover"),
        }
    }
}

impl Default for SecretDistributionType {
    fn default() -> SecretDistributionType {
        Self::Split
    }
}




