/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretDistributionDocData {
    #[serde(rename = "distributionType")]
    pub distribution_type: crate::models::SecretDistributionType,
    #[serde(rename = "metaPassword")]
    pub meta_password: Box<crate::models::MetaPasswordRequest>,
    #[serde(rename = "secretMessage")]
    pub secret_message: Box<crate::models::EncryptedMessage>,
}

impl SecretDistributionDocData {
    pub fn new(
        distribution_type: crate::models::SecretDistributionType,
        meta_password: crate::models::MetaPasswordRequest,
        secret_message: crate::models::EncryptedMessage,
    ) -> SecretDistributionDocData {
        SecretDistributionDocData {
            distribution_type,
            meta_password: Box::new(meta_password),
            secret_message: Box::new(secret_message),
        }
    }
}
