/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SerializedKeyManager {
    #[serde(rename = "dsa")]
    pub dsa: Box<crate::models::SerializedDsaKeyPair>,
    #[serde(rename = "transport")]
    pub transport: Box<crate::models::SerializedTransportKeyPair>,
}

impl SerializedKeyManager {
    pub fn new(
        dsa: crate::models::SerializedDsaKeyPair,
        transport: crate::models::SerializedTransportKeyPair,
    ) -> SerializedKeyManager {
        SerializedKeyManager {
            dsa: Box::new(dsa),
            transport: Box::new(transport),
        }
    }
}
