/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SerializedDsaKeyPair {
    #[serde(rename = "keyPair")]
    pub key_pair: Box<crate::models::Base64EncodedText>,
    #[serde(rename = "publicKey")]
    pub public_key: Box<crate::models::Base64EncodedText>,
}

impl SerializedDsaKeyPair {
    pub fn new(
        key_pair: crate::models::Base64EncodedText,
        public_key: crate::models::Base64EncodedText,
    ) -> SerializedDsaKeyPair {
        SerializedDsaKeyPair {
            key_pair: Box::new(key_pair),
            public_key: Box::new(public_key),
        }
    }
}
