/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserSignature {
    /// distributed vault, unique across the entire system
    #[serde(rename = "vaultName")]
    pub vault_name: String,
    #[serde(rename = "device")]
    pub device: Box<crate::models::DeviceInfo>,
    #[serde(rename = "publicKey")]
    pub public_key: Box<crate::models::Base64EncodedText>,
    #[serde(rename = "transportPublicKey")]
    pub transport_public_key: Box<crate::models::Base64EncodedText>,
}

impl UserSignature {
    pub fn new(
        vault_name: String,
        device: crate::models::DeviceInfo,
        public_key: crate::models::Base64EncodedText,
        transport_public_key: crate::models::Base64EncodedText,
    ) -> UserSignature {
        UserSignature {
            vault_name,
            device: Box::new(device),
            public_key: Box::new(public_key),
            transport_public_key: Box::new(transport_public_key),
        }
    }
}
