/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserSecurityBox {
    #[serde(rename = "vaultName")]
    pub vault_name: String,
    #[serde(rename = "signature")]
    pub signature: Box<crate::models::Base64EncodedText>,
    #[serde(rename = "keyManager")]
    pub key_manager: Box<crate::models::SerializedKeyManager>,
}

impl UserSecurityBox {
    pub fn new(vault_name: String, signature: crate::models::Base64EncodedText, key_manager: crate::models::SerializedKeyManager) -> UserSecurityBox {
        UserSecurityBox {
            vault_name,
            signature: Box::new(signature),
            key_manager: Box::new(key_manager),
        }
    }
}


