/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VaultDoc {
    #[serde(rename = "vaultName")]
    pub vault_name: String,
    #[serde(rename = "signatures")]
    pub signatures: Vec<crate::models::UserSignature>,
    #[serde(rename = "pendingJoins")]
    pub pending_joins: Vec<crate::models::UserSignature>,
    #[serde(rename = "declinedJoins")]
    pub declined_joins: Vec<crate::models::UserSignature>,
}

impl VaultDoc {
    pub fn new(vault_name: String, signatures: Vec<crate::models::UserSignature>, pending_joins: Vec<crate::models::UserSignature>, declined_joins: Vec<crate::models::UserSignature>) -> VaultDoc {
        VaultDoc {
            vault_name,
            signatures,
            pending_joins,
            declined_joins,
        }
    }
}


