/*
 * Meta Secret Core Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// VaultInfoStatus : `Member`: Device is a member of a vault. `Pending`: Device is waiting to be added to a vault. `Declined`: Vault members declined to add a device into the vault. `NotFound`: Vault not found `Unknown`: Device can't get any information about the vault, because its signature is not in members or pending list

/// `Member`: Device is a member of a vault. `Pending`: Device is waiting to be added to a vault. `Declined`: Vault members declined to add a device into the vault. `NotFound`: Vault not found `Unknown`: Device can't get any information about the vault, because its signature is not in members or pending list
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VaultInfoStatus {
    #[serde(rename = "Member")]
    Member,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Declined")]
    Declined,
    #[serde(rename = "NotFound")]
    NotFound,
    #[serde(rename = "Unknown")]
    Unknown,
}

impl ToString for VaultInfoStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Member => String::from("Member"),
            Self::Pending => String::from("Pending"),
            Self::Declined => String::from("Declined"),
            Self::NotFound => String::from("NotFound"),
            Self::Unknown => String::from("Unknown"),
        }
    }
}

impl Default for VaultInfoStatus {
    fn default() -> VaultInfoStatus {
        Self::Member
    }
}
