VERSION 0.8
FROM scratch
ENV RUST_VERSION="1.84.1"

generate-cargo-chef-recipe:
    FROM lukemathwalker/cargo-chef:latest-rust-${RUST_VERSION}-bookworm
    COPY . .
    RUN cargo chef prepare --recipe-path recipe.json
    SAVE ARTIFACT recipe.json AS LOCAL recipe.json

builder:
    FROM rust:${RUST_VERSION}-bookworm

    RUN rustup component add rustfmt

    # Install sccache (cargo is too slow)
    ENV SCCACHE_VERSION="v0.9.0"
    ENV SCCACHE_ARTIFACT=sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl
    ENV SCCACHE_BUNDLE=${SCCACHE_ARTIFACT}.tar.gz
    #RUN cargo install sccache@${SCCACHE_VERSION}
    ENV RUSTC_WRAPPER=sccache

    RUN wget https://github.com/mozilla/sccache/releases/download/${SCCACHE_VERSION}/${SCCACHE_BUNDLE} \
        && tar xzf ${SCCACHE_BUNDLE} \
        && mv ${SCCACHE_ARTIFACT}/sccache /usr/local/bin/sccache \
        && chmod +x /usr/local/bin/sccache

    # Install cargo-chef
    RUN cargo install cargo-chef --locked

    # Cache dependencies with cargo chef
    COPY recipe.json .
    RUN cargo chef cook --release --recipe-path recipe.json

meta-server-builder:
    FROM +builder
    COPY . .
    WORKDIR meta-server
    RUN cargo build --release
    SAVE ARTIFACT /target

build-meta-server-image:
    FROM debian:bookworm
    WORKDIR /app
    COPY +meta-server-builder/target/release/meta-server .
    CMD ./meta-server
    SAVE IMAGE --push ghcr.io/meta-secret/meta-secret-server:latest

wasm-build:
    FROM +builder

    #RUN cargo install wasm-pack slooooow
    RUN cargo install wasm-pack --version 0.13.1 --locked

    # Copy all source files first
    COPY . .

    # Then build the wasm package
    WORKDIR /wasm
    RUN wasm-pack build --target web
    SAVE ARTIFACT pkg

wasm-build-local:
    FROM +wasm-build
    SAVE ARTIFACT pkg AS LOCAL web-cli/ui/pkg

web-build:
    FROM node:23.5.0-bookworm

    ENV PROJECT_UI_DIR=web-cli/ui

    # Cache npm dependencies
    WORKDIR ${PROJECT_UI_DIR}
    COPY ${PROJECT_UI_DIR}/package.json .
    RUN npm install && npm install --dev

    COPY +wasm-build/pkg ./pkg

    WORKDIR /
    COPY . .

    WORKDIR ${PROJECT_UI_DIR}
    RUN --no-cache npm install && npm run build
    SAVE IMAGE --push ghcr.io/meta-secret/meta-secret-web:latest

app-test:
    FROM +builder
    COPY . .
    WORKDIR meta-secret

    RUN --no-cache cargo test --release
