name = "meta-server-serverless"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

kv_namespaces = [
    { binding = "meta-secret", id = "7b8e227565d444e79941386b44f9adec", preview_id = "10da8c22054f455a8291bf8d355cf533"}
]

[build]
command = "cargo install -q worker-build && worker-build --release"
