name: "Core Deployment"

on:
  workflow_dispatch:

  # Temporary disable automatic build
  #push:
    #branches:
    #  - main
    #paths:
    #  - '.github/workflows/core.yml'
    #  - 'core/**'

jobs:
  core-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            core/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate rust models
        working-directory: schema
        run: |
          npm install @openapitools/openapi-generator-cli -g
          make clean generate_schema

      - name: Publish core
        working-directory: core
        run: |
          cargo test
          cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
